### ISSUE TITLE
Custom Alert Dialog for Authentication

### ISSUE THREAD

**Issue by Mobiversa** [adorsys/fingerprint-android#15]
Hi Team,
I have tried to create a custom alert dialog but it won't work here.

**Comment by luckyhandler** [comment]
This library doesn't support using a custom dialog as stated in the readme in the library description:

```
show a system fingerprint dialog / biometric dialog without having to consider the API level or write boilerplate code
```

**Comment by luckyhandler** [comment]
Btw, as I don't have any right to do that, the issue can be closed @francis-pouatcha

**Comment by francis-pouatcha** [comment]
Hello Nino, i can give you access if you don't mind?

**Comment by luckyhandler** [comment]
Would be great

**Comment by francis-pouatcha** [comment]
Sent you admin invite.
