### ISSUE TITLE
Handling new FingerPrint enrolled on Phone

### ISSUE THREAD

**Issue by othreecodes** [adorsys/fingerprint-android#8]
Hi, Thanks for this awesome Library.

How do you handle when a user enrolls a new fingerprint via the phone settings

This is required for security reasons to prompt a password in this case

**Comment by luckyhandler** [comment]
Hey @othreecodes, if the user enrolls another fingerprint, the system still simply returns true.  So the user will be able to unlock or whatever you are trying to achieve. We don't get feedback on the fingerprint itself, only true or false

**Comment by luckyhandler** [comment]
@othreecodes By the way, thanks for the kudos. I will close this issue as handling fingerprint changes is nothing this library is meant for, if you don't mind...
